version: '3.8'
services:
  api:
    build: .
    container_name: user-container
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=docker
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DOCKER_DSN=${DOCKER_DSN}
    networks:
      - app-network
    restart: always

  # sell:
  #   build: 
  #     context: .
  #     dockerfile: ./src/sell/Dockerfile
  #   container_name: sell-container
  #   ports:
  #     - "8001:8080"
  #   environment:
  #     - APP_ENV=docker
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
