version: '3.8'
services:
  api:
    build: .
    container_name: go-api-container
    ports:
      - "8080:8080"  
    networks:
      - app-network
    restart: always

networks:
  app-network:  # Define custom network
    driver: bridge
